[package]
name = "prusic"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
crossterm = "0.29.0"
dirs = "6.0.0"
id3 = "1.17.1"
rand = "0.10.2"
ratatui = "0.30.2"
rodio = { 
    version = "0.22.2",
    features = [
        "playback",
        "symphonia-all"
    ]
}
walkdir = "2.5.0"
